all:
	+$(MAKE) -C VL53L1X_API_2.2.1/API/core/src
	+$(MAKE) -C VL53L1X_API_2.2.1/API/platform/src

clean:
	+$(MAKE) clean -C VL53L1X_API_2.2.1/API/core/src
	+$(MAKE) clean -C VL53L1X_API_2.2.1/API/platform/src