all:
	+$(MAKE) -C NemaTode/src
	+$(MAKE) -C ptpcam
	+$(MAKE) -C OPT3101
	+$(MAKE) -C OPT3101/serialLib
clean:
	+$(MAKE) clean -C NemaTode/src
	+$(MAKE) clean -C ptpcam
	+$(MAKE) clean -C OPT3101
	+$(MAKE) clean -C OPT3101/serialLib