#:import random random

<ScatterTextWidget>:
    orientation: "vertical"
    TextInput:
        id: input
        font_size: 75
        size_hint_y: None
        height: 100
        text: "Default"
        on_text: root.gen_rand_color()
    FloatLayout:
        Scatter:
            Label:
                id: my_label
                text: input.text
                font_size: 75
                color: root.text_color
    BoxLayout:
        size_hint_y: None
        height: 150
        Label:
            text: input.text[:3][::-1]
            font_size: 75
            color: root.text_color
        Label:
            text: input.text[-3:][::-1]
            font_size: 75
            color: root.text_color